# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

solver_rcpp <- function(reward, reward_scores, cost, sample_weights, tie_breaker, clusters, budget, target_with_covariates, paired_inference, num_bootstrap, num_threads, seed) {
    .Call(`_maq_solver_rcpp`, reward, reward_scores, cost, sample_weights, tie_breaker, clusters, budget, target_with_covariates, paired_inference, num_bootstrap, num_threads, seed)
}

convex_hull_rcpp <- function(reward, cost) {
    .Call(`_maq_convex_hull_rcpp`, reward, cost)
}

